### PR TITLE
Rent and return fixed issues

### PR DESCRIPTION
**Pull request by jtlester**
Everything for those 2 screen are working great now. We only need these 2 for tomorrow (along with date registered for the other classes which are good as well)

### CODE REVIEW

**Comment by evanlws12** [comment]
Ok I can't merge this for some reason. I think you're trying to merge 4 different pull requests when all 3 of our files are different. See if you can merge danielles into yours first and then create a pull request from yours

**Comment by jtlester** [comment]
I did merge hers yesterday, maybe its because zach merged his and mine wasnt updated with renew?

**Comment by evanlws12** [comment]
That might be it... what files do we need then? i can just copy/paste the important ones

**Comment by jtlester** [comment]
Bicycle, user/bicycle/worker views, peon ( added a change status method in there, pretty sure thats all I added), rent and return views. After you add those in ill sync mine and test it before I go to bed tonight to make sure your master works for tomorrow

**Comment by evanlws12** [comment]
Alright I'm making changes now. I'll make a pull request in an hour or so so you can test it tomorrow. I'm not doing any database stuff and I can test everything else so we should be ok

**Comment by jtlester** [comment]
Ok awesome sounds good, ill do it in the morning then and test it

**Pull request closed without merging**
